<?php

namespace spaf\simputils\yii\db;

use spaf\simputils\models\DateTime;
use spaf\simputils\traits\SimpleObjectTrait;

class Command extends \yii\db\Command {
	use SimpleObjectTrait;

	public function bindValue($name, $value, $dataType = null) {
		if ($value instanceof DateTime) {
			$value = $value->for_system;
		}
		return parent::bindValue($name, $value, $dataType); // TODO: Change the autogenerated stub
	}

}
